<?php
return array(

    // The path to your asset manifest, most likely have been generated by a
    // task runner such as Gulp or Grunt. Paths will be relative to your craft
    // base directory, unless you supply an absolute directory path.

    'manifestPath' => 'resources/assets/assets.json',

    // The base path to your assets. Again, this is relative to your craft base
    // directory, unless you supply an absolute directory path. The path will
    // always be appended to the filename that is passed though the `rev()`.

    'assetsBasePath' => null,

    // A prefix to apply to your assets when they are output from the plugin. It
    // would be useful to set this if the paths in your manifest file are likely
    // to be different to the final asset url different

    'assetUrlPrefix' => null,

);
